### ISSUE TITLE
Inconsistent energies with GHMC integrator

### ISSUE THREAD

**Issue by gregoryross** [choderalab/openmmtools#118]
In version 0.8.2 of `openmmtools`, the custom integrator `GHMCIntegrator` is able to output energies before and after an integration step. These global variables are called `potential_old` and `potential_new`, respectively. I've been comparing these energies with ones extracted via `context.getState(getEnergy=True)`. For normal 'equilibrium' MD, the energies taken from the integrator match the energies from `getState()` excellently. However, when modifying the non-bonded parameters with `setParticleParameters()` and `updateParametersInContext()`, the energies calculated with the methods above disagree. (I'm modifying the non-bonded parameters for non-equilibrium candidate Monte Carlo.) Tagging @jchodera, @pgrinaway and @juliebehr in case this is related to their `Perses` project.

I've created some minimal code to highlight this behavior. I'm modifying the LJ parameters of a single water molecule in-between two single steps of the GHMC integrator.

```
from simtk import openmm, unit
from simtk.openmm import app
from openmmtools import integrators
from openmmtools.testsystems import WaterBox

# Creating a box of water:
size = 20.0*unit.angstrom     # The length of the edges of the water box.
temperature = 300*unit.kelvin
pressure = 1*unit.atmospheres
wbox = WaterBox(box_edge=size,nonbondedMethod=app.PME,cutoff=9*unit.angstrom,ewaldErrorTolerance=1E-6)
ghmc = integrators.GHMCIntegrator(temperature, 1/unit.picosecond, 0.1*unit.femtoseconds)

context = openmm.Context(wbox.system, ghmc)
context.setPositions(wbox.positions)
context.setVelocitiesToTemperature(temperature)

force = wbox.system.getForce(2)       # Non-bonded force.

#      Getting the energy BEFORE the parameters are perturbed
ghmc.step(1)
state = context.getState(getEnergy=True)
potential_old = state.getPotentialEnergy()/unit.kilojoule_per_mole
print('old',potential_old,ghmc.getGlobalVariableByName('potential_new'))

#      Perturbation. Reducing LJ parameters by 10%
force.setParticleParameters(0,charge=-0.834,sigma=0.3150752406575124*0.9,epsilon=0.635968*0.9)
force.updateParametersInContext(context)

#      Getting the energy AFTER the parameters have been perturbed.
state = context.getState(getEnergy=True)
potential_new = state.getPotentialEnergy()/unit.kilojoule_per_mole
ghmc.step(1)    
print('new',potential_new,ghmc.getGlobalVariableByName('potential_new'))

#      Resetting the parameters
force.setParticleParameters(0,charge=-0.834,sigma=0.3150752406575124,epsilon=0.635968)
force.updateParametersInContext(context)
```
As you should see, the printed energies tend to disagree. The effect is more pronounced if the above 'propagation, perturbation, propagation` dynamics is iterated over. I've been testing this on CPUs and have some early indications this is occurring on GPUs too. 

Any pointers as to why this is happening would be greatly appreciated! Thanks.

**Comment by jchodera** [comment]
The `GHMCIntegrator` comes from [here](https://github.com/choderalab/openmmtools/blob/master/openmmtools/integrators.py#L526). Make sure you have done `conda install --yes openmmtools`and have the latest version.

**Comment by jchodera** [comment]
I can confirm that I can reproduce this on `linux` with the latest `openmm` dev version on all platforms:
```
Reference
('old', -1099.399222886602, -1099.399222886602)
('new', -1108.8311642686756, -1171.034619608429)
CPU
('old', -1080.0652859543527, -1080.0652859543527)
('new', -1089.4889950701333, -1132.4351299072594)
CUDA
('old', -1097.2111971642298, -1097.2111971642298)
('new', -1106.6459213419585, -1166.016459766921)
OpenCL
('old', -1091.4301227446267, -1091.4301227446267)
('new', -1100.8756593493308, -1155.24859315512)
```

**Comment by gregoryross** [comment]
Thanks John. I can confirm that I have the latest version of `openmmtools`.

I should add that the `old` energies also disagree when the iterating the 'propagation, perturbation, propagation' protocol. i.e. having a `for loop` starting at the first `ghmc.step(1)` to the last `force.updateParametersInContext(context)`.

**Comment by jchodera** [comment]
> Thanks John. I can confirm that I have the latest version of openmmtools.

Oh! I just meant that anyone trying to reproduce this (like @peastman) should have the latest version of `openmmtools` installed.

**Comment by jchodera** [comment]
Wait, I don't think this test is quite correct.

The part where you print out the potential after the Context update should be:
```
#      Getting the energy AFTER the parameters have been perturbed.
state = context.getState(getEnergy=True)
potential_new = state.getPotentialEnergy()/unit.kilojoule_per_mole
ghmc.step(1)    
print('new',potential_new,ghmc.getGlobalVariableByName('potential_old'))
```
whereas you had `potential_new` instead of `potential_old`.

I now get the correct results:
```
OpenCL
('old', -1093.5346204390662, -1093.5346204390662)
('new', -1093.5346204390662, -1093.5346204390662)
```

**Comment by jchodera** [comment]
No, wait, my bugfix had a bug. I had commented out the `updateParametersInContext`. Now, I do get something wrong:
```
Reference
('old', -1098.1359088701913, -1098.1359088701913)
('new', -1107.6009570234753, -1098.1359088701913)
```
While the `context.getState()` energy changed after the parameters changed, the `potential_old` was not updated, despite the `GHMCIntegrator` containing
```
        self.addComputeGlobal("potential_old", "energy")
```
at the beginning of the step. Somehow, `CustomIntegrator` thinks it does not need to update the global variable `potential_old` or recompute the energy at the beginning of the step *despite* the fact that the `NonbondedForce` parameters have changed.

**Comment by jchodera** [comment]
I'm trying to figure out why this might be the case. Calling [`NonbondedForce.updateParametersInContext()`](https://github.com/pandegroup/openmm/blob/master/openmmapi/src/NonbondedForceImpl.cpp#L279) triggers a [call to `copyParametersToContext()`](https://github.com/pandegroup/openmm/blob/master/platforms/opencl/src/OpenCLKernels.cpp#L2120) which then [calls](https://github.com/pandegroup/openmm/blob/master/platforms/opencl/src/OpenCLKernels.cpp#L2192) [`cl.invalidateMolecules()](https://github.com/pandegroup/openmm/blob/master/platforms/opencl/src/OpenCLContext.cpp#L947), which then should call the `CustomIntegrator` [`ReorderListener`](https://github.com/pandegroup/openmm/blob/master/platforms/opencl/src/OpenCLKernels.cpp#L7071-L7130). I'm just not sure if this invalidates the potential energy as well.

**Comment by jchodera** [comment]
Do we need some way to trigger the following code when `updateParametersInContext()` are called? I'm not seeing how [this actually happens at the beginning of a timestep](https://github.com/pandegroup/openmm/blob/master/platforms/opencl/src/OpenCLKernels.cpp#L7795-L7798):
```
    if (cl.getAtomsWereReordered()) {
        forcesAreValid = false;
        validSavedForces.clear();
    }
```

**Comment by jchodera** [comment]
Is it simply the case that we (as users) neglected to call `integrator.stateChanged()`?

From the [`CustomIntegrator.h` header](https://github.com/pandegroup/openmm/blob/master/openmmapi/include/openmm/CustomIntegrator.h#L549-L552):
```C++
    /**
     * When the user modifies the state, we need to mark that the forces need to be recalculated.
     */
    void stateChanged(State::DataType changed);
```

**Comment by jchodera** [comment]
Oh, no, I see that's `protected`.

**Comment by jchodera** [comment]
I think I see the issue.

In [`CustomNonbondedForceImpl.cpp`](https://github.com/pandegroup/openmm/blob/master/openmmapi/src/NonbondedForceImpl.cpp#L278-L280), a call to `updateParametersInContext()` omits a call to `context.getIntegrator().stateChanged()`:
```
void NonbondedForceImpl::updateParametersInContext(ContextImpl& context) {
    kernel.getAs<CalcNonbondedForceKernel>().copyParametersToContext(context, owner);
}
```
This is presumably the case for many other forces as well.

@peastman: What do you think?

**Comment by peastman** [comment]
That isn't what `stateChanged()` was originally for, but it would probably make sense to start using it for that.  It was meant to indicate that state information had changed (positions, velocities, etc.).  That was before we added the `updateParametersInContext()` methods, so state information was the only thing that could change during a simulation, and hence the only thing that could affect forces.  But now that force parameters can also change, we need to notify the integrator about that too.  And rather than adding a new mechanism, I think it would be fine to just use the existing `stateChanged()` mechanism in that case.

So yes, we should make *all* `updateParametersInContext()` methods call that.  One awkward thing is that the argument needs to specify which aspect of the state has changed.  And of course, no aspect of the state has changed.  But in practice, it doesn't really matter.  The only integrators that implement that function are CustomIntegrator and RPMDIntegrator, and neither of them cares what the argument value is.  So as a convention, let's pass `State::Energy` as the argument (indicating that the energy has changed, even though no state information has changed).

**Comment by jchodera** [comment]
Do you want @gregoryross to attempt a PR, or would you rather do it, @peastman?

**Comment by jchodera** [comment]
Also, wouldn't `State::Parameters` be more appropriate here than `State::Energy`?

**Comment by peastman** [comment]
I can do it.  `State::Parameters` means that parameter values have changed (that is, someone has called `setParameter()` on the Context), which isn't the case here.

**Comment by gregoryross** [comment]
That's great. Thank you both.

**Comment by gregoryross** [comment]
Thanks a lot @jchodera and @peastman, the latest version has fixed this issue and more advanced versions of it. 

For the record, @jchodera was correct, there was a typo in my minimal example. The penultimate code section should have read:
```
#      Getting the energy AFTER the parameters have been perturbed.
state = context.getState(getEnergy=True)
potential_new = state.getPotentialEnergy()/unit.kilojoule_per_mole
ghmc.step(1)    
print('new',potential_new,ghmc.getGlobalVariableByName('potential_old'))
```

**Comment by gregoryross** [comment]
@peastman and @jchodera I've reopened this issue because while the `openmm` update fixes the GHMC integrator, it doesn't work for compound integrators. Possibly there is some confusion with `context.getIntegrator().stateChanged()`? 

Below is my minimal code example. It's the same as the original, except that a compound integrator is created.
```
from simtk import openmm, unit
from simtk.openmm import app
from openmmtools import integrators
from openmmtools.testsystems import WaterBox

# Creating a box if water
size = 20.0*unit.angstrom     # The length of the edges of the water box.
temperature = 300*unit.kelvin
pressure = 1*unit.atmospheres
wbox = WaterBox(box_edge=size,nonbondedMethod=app.PME,cutoff=9*unit.angstrom,ewaldErrorTolerance=1E-6)

#      Creating the compound integrator
ghmc = integrators.GHMCIntegrator(temperature, 1/unit.picosecond, 0.1*unit.femtoseconds)
langevin = openmm.LangevinIntegrator(temperature, 1.0/unit.picoseconds, 2.0*unit.femtoseconds)

integrator = openmm.CompoundIntegrator()
integrator.addIntegrator(langevin)
integrator.addIntegrator(ghmc)
integrator.setCurrentIntegrator(1)

context = openmm.Context(wbox.system, integrator)
context.setPositions(wbox.positions)
context.setVelocitiesToTemperature(temperature)

force = wbox.system.getForce(2)       # Non-bonded force.

#      Getting the energy BEFORE the parameters are perturbed
ghmc.step(1)
state = context.getState(getEnergy=True)
potential_old = state.getPotentialEnergy()/unit.kilojoule_per_mole
print('old',potential_old,ghmc.getGlobalVariableByName('potential_new'))

#      Perturbation. Reducing LJ parameters by 10%
force.setParticleParameters(0,charge=-0.834,sigma=0.3150752406575124*0.9,epsilon=0.635968*0.9)
force.updateParametersInContext(context)

#      Getting the energy AFTER the parameters have been perturbed
state = context.getState(getEnergy=True)
potential_new = state.getPotentialEnergy()/unit.kilojoule_per_mole
ghmc.step(1)     # The 'old' energy for one step should be the energy immediately after the perturbation
print('new',potential_new,ghmc.getGlobalVariableByName('potential_old'))

#      Resetting the parameters
force.setParticleParameters(0,charge=-0.834,sigma=0.3150752406575124,epsilon=0.635968)
force.updateParametersInContext(context)
```

**Comment by jchodera** [comment]
Good catch! `CompoundIntegrator` should have a `integrator.stateChanged()` method that passes its argument on to `integrator.stateChanged()` for all its member integrators.

**Comment by peastman** [comment]
That's exactly right.  I just sent a PR with the fix.

**Comment by gregoryross** [comment]
I can confirm that the new `dev` build of `protoms` correctly updates integrators and compound integrators when forcefield parameters are changed with `setParticleParameters` and `updateParametersInContext`. 

Thanks @peastman and @jchodera for your help!
