### ISSUE TITLE
Add getTemperature and setTemperature methods to integrators coupled to heat bath

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/openmmtools#129]
When creating/applying itself to a `Context`, the new `ThermodynamicState` class currently adds an `AndersenThermostat` if the integrator does keep the temperature of the system constant. `ThermodynamicState` considers thermostated integrators those that expose `get/setTemperature()` methods. Any objection if I add these in the PR I'm currently working on?

**Comment by jchodera** [comment]
I'm not sure I fully understand. We shouldn't need an Andersen thermostat if the integrator already has a way of ensuring the stationary distribution at the given temperature is the only one preserved.

And which class would you add the temperature getters and setters to?

I think our focus should be on constructing a workable MCMC scheme for chaining together MC blocks to do some minimal kinds of sampling: GHMC, VVVR, MonteCarloRotation, MonteCarloTranslation.

**Comment by andrrizzi** [comment]
> We shouldn't need an Andersen thermostat if the integrator already has a way of ensuring the stationary distribution at the given temperature

Sorry if I wasn't clear. This is exactly what `ThermodynamicState` does when creating a `Context`, but to do so, it needs to infer somehow if the integrator takes care of the temperature or not, and right know it does it by checking if the integrator exposes `get/setTemperature()`.

> And which class would you add the temperature getters and setters to?

Based on what it's currently in the `integrators` module, I'd say `AndersenVelocityVerletIntegrator`, `MetropolisMonteCarloIntegrator`, `HMCIntegrator`, `GHMCIntegrator`, `VVVRIntegrator`.

**Comment by andrrizzi** [comment]
This is blocking so I'll start implementing it. I'll do it in an independent branch so that it'll be easy to review.

**Comment by jchodera** [comment]
> Based on what it's currently in the integrators module, I'd say AndersenVelocityVerletIntegrator, MetropolisMonteCarloIntegrator, HMCIntegrator, GHMCIntegrator, VVVRIntegrator.

Ah, OK! That's fine!

**Comment by jchodera** [comment]
This was fixed by #130.
