### ISSUE TITLE
Allow users to specify rule for velocity flipping on accept or reject for Metropolized LangevinIntegrator

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#160]
We should triple-check that we have the velocity flipping correct for all splittings involving Metropolization, such as:
```
O { V R V } O
{ O V R V O }
{ V R O R V }
```
and allow users to specify whether they want to flip on accept or reject.

**Comment by gregoryross** [comment]
@jchodera Looks to me like the velocities are indeed flipped upon rejection, as shown [here](https://github.com/choderalab/openmmtools/blob/master/openmmtools/integrators.py#L1245-L1258). From what I can tell, this seems to require `measure_shadow_work=True` for Metropolization to work properly. Is that correct @maxentile and @pgrinaway? If so, shouldn't `measure_shadow_work` be automatically set to `true` when either `verify_metropolization()` or `begin_metropolize()` are called?

**Comment by pgrinaway** [comment]
I think we actually do force `measure_shadow_work` to `True` [(see here)](https://github.com/choderalab/openmmtools/blob/master/openmmtools/integrators.py#L909)

**Comment by gregoryross** [comment]
Okay, great. Sorry, I missed that. 

I think this issue has been fully addressed, so I'll close it.
