### ISSUE TITLE
Add nan rejection to end of un-Metropolized MCMC blocks?

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#195]
Even with g-BAOAB, we sometimes run into `nan`s, so it would be useful to integrate some infrastructure for checking for `nan`s at the end of un-Metropolized MCMC blocks and restoring the old sampler state (and tracking statistics on `nan`s) if one occurs.

**Comment by andrrizzi** [comment]
I've already implemented something like this in the base class `BaseIntegratorMove` for MCMC Moves based on integrators. Is [this](https://github.com/choderalab/openmmtools/blob/master/openmmtools/mcmc.py#L651) what you had in mind?

**Comment by jchodera** [comment]
Yes, that's exactly it! I'll be sure to use this MCMC framework when migrating http://github.com/choderalab/sams over to `openmmtools.samplers.sams` this week.
