### ISSUE TITLE
Rename AlchemicalFactory to AbsoluteAlchemicalFactory

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#204]
We'll soon have a `RelativeAlchemicalFactory` or `HybridAlchemicalFactory` too, so it would be useful to make this change sooner rather than later.

**Comment by andrrizzi** [comment]
Sorry I changed the original name. I thought we could implement relative factories as methods of `AlchemicalFactory` instead of having different classes, but I don't know much about the implementation details of the current `RelativeAlchemicalFactory` and `HybridAlchemicalFactory`. Do you think that won't be possible/make sense?

**Comment by jchodera** [comment]
They will share zero infrastructure (aside from the utility to recode reaction field as a Custom nonbonded Force,you which may not even belong in alchemy) andmost no options in common. It would be a total mess if we had to implement them both in the same class unless we used a ton of separate private methods or classes, at which point we may as well just make them separate classes.

Sorry for not catching this earlier. We should fix this now so we don't run into trouble later.

We can also make alchemy a subpackage and split the AlchemicalRegion and AlchemicalState classes off into separate modules, importing them into the openmmtools.alchemy namespace. We can then bring in the HybridTopologyAlchemicalFactory from Perses once it stabilizes.

**Comment by andrrizzi** [comment]
Alright, I'll fix it today. Is anybody else using the new alchemy beside YANK?

**Comment by jchodera** [comment]
Not sure, honestly.

But let's also toss up a warning that the API is not necessarily final, like I have in the docs for my SAMS PR.

**Comment by andrrizzi** [comment]
> But let's also toss up a warning that the API is not necessarily final

I can do that, but the alchemy API will have to be final when we'll release YANK 1.0, which will happen soon. What else do you think is not final? The recoding of reaction field?

**Comment by jchodera** [comment]
That's what I was worried about, yes. We might want to move that one method.

Also, we just need a warning in the docs; the code doesn't need to emit a warning.

**Comment by andrrizzi** [comment]
Ok! Not sure if it's possible, but what about give a warning in the docs about that method alone in this case? Just so that people are not discouraged to use the rest of the module.

**Comment by jchodera** [comment]
Actually, it looks like we have a global warning at the top of the docs:
http://openmmtools.readthedocs.io/en/latest/

Instead, there's probably a way to tell `autosummary` and `autodoc` that certain modules, classes, or methods are either experimental or deprecated. Let me see if I can figure this out.

**Comment by jchodera** [comment]
I guess we could put sphinx restructuredtext into the docstrings of individual module, classes, or methods that uses [`note`](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-note), [`warning`](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-warning), or [`deprecated`](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-deprecated), but I'm trying to see if [`numpydoc`](https://pypi.python.org/pypi/numpydoc?) provides some alternatives.

**Comment by jchodera** [comment]
It looks like [`numpydoc` guidelines](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#sections) recommend using `note`:
```
.. note:: Deprecated in NumPy 1.6.0
          `ndobj_old` will be removed in NumPy 2.0.0, it is replaced by
          `ndobj_new` because the latter works also with array subclasses.
```

**Comment by jchodera** [comment]
I'd be up for marking unstable API elements with `note` or `warning` and deprecated ones with `deprecated`.

**Comment by andrrizzi** [comment]
Thanks for looking into it! I'll open a PR fixing this soon.
