### ISSUE TITLE
Add option to AbsoluteAlchemicalFactory to disable long-range correction in CustomNonbondedForce when alchemical switching will be used

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#217]
In cases where we want to alchemically switch `lambda_sterics` by updating its value every timestep, a huge (100x) slowdown is noted because the dispersion correction is numerically integrated (on the CPU) each time `lambda_sterics` is updated. To avoid this, we should add an option to `AbsoluteAlchemicalFactory` to disable the long-range correction in `CustomNonbondedForce` to allow efficient integration in these cases.

cc: https://github.com/pandegroup/openmm/issues/1832
cc: https://github.com/choderalab/openmmtools/issues/201#issuecomment-306965778

**Comment by andrrizzi** [comment]
This was added in #218 .
