### ISSUE TITLE
Remove parmed dependencies for testsystems

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#224]
Some testsystems require `parmed` instead of the `simtk.openmm.app.AmberPrmtopFile`, such as [here](https://github.com/choderalab/openmmtools/blob/master/openmmtools/testsystems.py#L3452-L3453). We should remove this requirement since openmm should have all the requisite capabilities.

cc: #223

**Comment by mjw99** [comment]
./openmmtools/data/dhfr/prmtop is using the pre-AMBER 7 format, hence AmberPrmtopFile will not be able to parse it. We could update ./openmmtools/data/dhfr/{prmtop,inpcrd} to an updated AMBER 7 format?

**Comment by mjw99** [comment]
Duplicate of #539
