### ISSUE TITLE
Option to disable context cache?

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#230]
@andrrizzi : It looks like several people (including @pgrinaway) are having issues with some corner cases for the context cache. What do you think about adding an option to disable the caching aspects of the context cache so these folks can plow ahead and re-enable the context cache when the issues are addressed?

@pgrinaway is working on an issue to describe his problem. The odd slowdown with YANK's use of the rotation/displacement moves is the other case I know about at the moment.

**Comment by andrrizzi** [comment]
Sorry about this.

To deactivate the global context cache you just have to do
```python
openmmtools.cache.global_context_cache = openmmtools.cache.DummyContextCache()
```
This will recreate a `Context` everytime. To deactivate the context caching for single MCMCMoves you just have to initialize them like this
```python
move = AnyMCMCMove(..., context_cache=openmmtools.cache.DummyContextCache())
```

**Comment by andrrizzi** [comment]
Closing this to keep things clean. Feel free to reopen if it's still unclear how to disable the cache.
