### ISSUE TITLE
Context cache failure to access `set*`

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/openmmtools#231]
Unfortunately, I don't have a minimal example yet, but I did want to note that a few days ago, as I was trying to use the `ContextCache` with a `celery` worker, I ran into a strange bug. Using the `AlchemicalNonequilibriumLangevinIntegrator`, whenever it tried to recover a context and integrator, I got an exception that there was no attribute `set*` (including `setTemperature`, etc.).

 After some debugging, I noticed that the `AlchemicalNonequilibriumLangevinIntegrator` was becoming a regular `CustomIntegrator` somehow, but I'm not quite sure how or why.

This isn't super high priority, since I have a workaround for now, but since the `ContextCache` API is really awesome and convenient, it would be great to figure out what's going on.

**Comment by pgrinaway** [comment]
This possibly relates to #230 but I don't think disabling the cache function will help here.

**Comment by jchodera** [comment]
> After some debugging, I noticed that the AlchemicalNonequilibriumLangevinIntegrator was becoming a regular CustomIntegrator somehow, but I'm not quite sure how or why.

That's almost certainly due to [this line](https://github.com/choderalab/openmmtools/blob/master/openmmtools/cache.py#L385):
```
        context_integrator = context.getIntegrator()
```
This will only retrieve the swig-wrapped `Integrator` object, but won't retrieve any Python-based subclass of `Integrator`. We'll have to cache the `Integrator` object as well as the `Context` object in the LRU cache rather than use this idiom to retrieve an integrator from the `Context`.

I'm not sure if that's responsible for any of the other issues @pgrinaway notes, though!

**Comment by pgrinaway** [comment]
I think that might be responsible... I'm not quite sure. I seem to remember the other argument to `_copy_integrator_state` also losing its attributes...maybe I made a mistake there though.

**Comment by jchodera** [comment]
It looks like performing a `copy.deepcopy()` on our Python integrators that subclass `openmm.CustomIntegrator` produces a new `openmm.CustomIntegrator`, without the Python wrapping:
```
>>> import copy
>>> from simtk import openmm, unit
>>> class WrappedIntegrator(openmm.CustomIntegrator):
...    def __init__(self, timestep):
...       super(WrappedIntegrator,self).__init__(timestep)
... 
>>> i = WrappedIntegrator(1.0)
>>> type(i)
<class '__main__.WrappedIntegrator'>
>>> j = copy.deepcopy(i)
>>> type(j)
<class 'simtk.openmm.openmm.CustomIntegrator'>
```
This suggests we may need to implement some sort of custom `copy` method for the base class we use to subclass `CustomIntegrator`.

**Comment by andrrizzi** [comment]
Hmm. That's weird. Right after the integrator is gotten with `context.getIntegrator()` we call `ThermostatedIntegrator.restore_interface()` [here](https://github.com/choderalab/openmmtools/blob/master/openmmtools/cache.py#L422-L431) and that should restore all setters and getters for integrators that inherit from `RestorableIntegrator`.

I'll see if I can reproduce the issue!

**Comment by jchodera** [comment]
> Hmm. That's weird. Right after the integrator is gotten with context.getIntegrator() we call ThermostatedIntegrator.restore_interface() here and that should restore all setters and getters for integrators that inherit from RestorableIntegrator.

Will that also add any of the other setters/getters added by `AlchemicalNonequilibriumLangevinIntegrator`, or will we have to create a `RestorableX` base class for each one of these things?

**Comment by andrrizzi** [comment]
> Will that also add any of the other setters/getters added by `AlchemicalNonequilibriumLangevinIntegrator`

It should add also those. @pgrinaway figured out that it's a problem with an incorrect hashing of the classes names in the celery workers. I'm working with him offline to debug this and fix the problem.

**Comment by jchodera** [comment]
Ah! Thanks!

**Comment by andrrizzi** [comment]
I believe this bug is due to the fact that `str.__hash__()` is non-deterministic from Python 3.3 up, so if you create an integrator in a process and send its serialization to a different one, `RestorableIntegrator` won't be able to match it to any subclass.

**Comment by jchodera** [comment]
[This comment](https://stackoverflow.com/questions/27954892/deterministic-hashing-in-python-3) suggests we use our own hash function such as [`zlib.alder32`](https://docs.python.org/3/library/zlib.html#zlib.adler32) or [`hashlib`](https://docs.python.org/3/library/hashlib.html) instead.

**Comment by andrrizzi** [comment]
Yeah, I went with adler32.
