### ISSUE TITLE
Many implicit testsystems are in vacuum

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/openmmtools#248]
There's a bug in `testsystems.handle_kwargs` where the dictionary is not updated correctly. This has the effect of creating `LysozymeImplicit`, `HostGuestImplicit` and `TolueneImplicit` in vacuum instead of implicit solvent if you don't explicitly specify the implicit solvent model in their constructors.

I'll open a PR to fix it (let's hope it doesn't break too many tests).

**Comment by jchodera** [comment]
Goodness, thanks for catching this!

**Comment by jchodera** [comment]
Let's cut a critical bugfix release when we get that fixed.
