### ISSUE TITLE
Where to put replace_reaction_field?

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/openmmtools#251]
Currently it's an instance method of `AbsoluteAlchemicalFactory`. The relative factory will surely want to use it too, so we should probably move it as a function at the `alchemy` module level at least. Are there any other plans for that feature?

**Comment by andrrizzi** [comment]
Also, is it ok if I make `replace_reaction_field` modifying the system in place instead of returning a new one? In most cases we won't need to keep the old one, and the extra copy make things slower. The user could still decide whether to make a copy before feeding it to the function in case it needs also the original system.

**Comment by jchodera** [comment]
I had intended to create an `openmmtools.forcefactories` or `openmmtools.forcefactory`, where methods or classes that create `Force` objects on demand (e.g. reaction field variants, restraint forces based on MDTraj DSL selections, etc) will live. How about that?

> Also, is it ok if I make replace_reaction_field modifying the system in place instead of returning a new one? In most cases we won't need to keep the old one, and the extra copy make things slower. The user could still decide whether to make a copy before feeding it to the function in case it needs also the original system.

What about adding an option to do that rather than doing it always?

**Comment by andrrizzi** [comment]
> I had intended to create an `openmmtools.forcefactories` or `openmmtools.forcefactory`

Sounds good. What about a slightly shorter name for the module like `openmmtools.forces`?

> What about adding an option to do that rather than doing it always?

Ok! I'll make it always return the system with a `return_copy` argument that defaults to `True`.

**Comment by andrrizzi** [comment]
Hmm. What if I put in `openmmtools.forces` an actual `UnshiftedReactionField(openmm.CustomNonbondedForce)` class (or some better name) that `replace_reaction_field` method uses?

**Comment by jchodera** [comment]
> Hmm. What if I put in openmmtools.forces an actual UnshiftedReactionField(openmm.CustomNonbondedForce) class (or some better name) that replace_reaction_field method uses?

I like it!

**Comment by jchodera** [comment]
Though, if we did that, we will need to be careful with `CustomNonbondedForce` subclasses (just like with `CustomIntegrators`) that we have to be careful to either avoid the use of class/object fields or come up with a base class that handles serialization properly. The "force factory that generates a `CustomNonbondedForce`" idiom avoids that issue, but as long as we're careful, we can do both.

I think I'd eventually love to find a way to make these Python subclasses serializable/pickleable in a more Pythonic way, but maybe we can brainstorm more about how to make that happen later.

**Comment by andrrizzi** [comment]
Great!

Technically the factory avoids the issue by putting everything inside a global/per-particle parameter. That's what I was thinking about doing here. The class would just be a convenience class, so that we won't have to specify the functional form of the force, and it will maybe offer a `copy_nonbonded_force` method to copy the correct the particle parameters.

**Comment by jchodera** [comment]
I guess the `UnshiftedReactionFieldForce` could take an optional `system` argument in its constructor that copies the particle parameters itself.

**Comment by andrrizzi** [comment]
Good idea!

**Comment by andrrizzi** [comment]
Hmm. We may not be adding back the exceptions as a `CustomBondForce` in the current implementation of `replace_reaction_field`. I'll modify the tests to make sure it's tested.

**Comment by andrrizzi** [comment]
Can a `System` have multiple `NonbondedForce`s? Because in this case we should probably pass a force to copy in the constructor rather than a system.

**Comment by jchodera** [comment]
>  Hmm. We may not be adding back the exceptions as a CustomBondForce in the current implementation of replace_reaction_field. I'll modify the tests to make sure it's tested.

Don't we leave the exceptions in `NonbondedForce`?

**Comment by andrrizzi** [comment]
Ah! Right, that's what I was missing, thanks!

**Comment by jchodera** [comment]
The problem with providing a `system` as input is that, for this to be convenient, it needs to zero out charges from the `system` passed as argument. That might make this an unexpected side effect unless very well documented. But at that point, it sounds weird initialize a force you always have to add back to the newly modified system:
```
# This is right
force = UnshiftedReactionFieldForce(system)
system.addForce(force)
# This might be wrong, since system is modified by the initializer?
system.addForce(UnshiftedReactionFieldForce(system))
```

**Comment by andrrizzi** [comment]
Yeah, that's not a replacement for `replace_reaction_field()`. I already have a first implementation on a branch. I will open a PR soon. Let me know what you think!
