### ISSUE TITLE
AbsoluteAlchemicalFactory does not support virtual sites

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#258]
We need to add virtual site support to [`AbsoluteAlchemicalFactory`](https://github.com/choderalab/openmmtools/blob/master/openmmtools/alchemy.py#L774-L850), which currently omits them.

cc: https://github.com/choderalab/yank/issues/720#issuecomment-318222114

**Comment by andrrizzi** [comment]
Thanks for catching it! I'll work on a fix.

**Comment by jchodera** [comment]
Let's also add a test for something with virtual sites, like a TIP4P-Ew water box!

**Comment by jchodera** [comment]
Note that @pgrinaway included support for virtual sites in the non-alchemical region [in `HybridTopologyFactory`](https://github.com/choderalab/perses/blob/distributed-rfep/perses/annihilation/new_relative.py#L184-L211) that may be of use here, and raised an exception if there were virtual sites in the alchemical region (as we should as well).
