### ISSUE TITLE
Mismatch in default/docstring for collision_rate in LangevinIntegrator

### ISSUE THREAD

**Issue by sgill2** [choderalab/openmmtools#260]
In `openmmtools.integrators.LangevinIntegrator` the actual default `collision_rate` is `1.0 / simtk.unit.picoseconds`, while the docstrings have the default listed as `91.0/simtk.unit.picoseconds`
https://github.com/choderalab/openmmtools/blob/master/openmmtools/integrators.py#L890-L971

**Comment by jchodera** [comment]
Good catch! Any chance you can contribute a PR to fix?

**Comment by sgill2** [comment]
Sure. The only thing is that I'm not 100% sure which portion should be fixed. I assume though the default value in `__init__` should be`91.0/simtk.unit.picoseconds`, to match with the rest of the integrators. I'll go make a PR in any case.
