### ISSUE TITLE
Pass to restrain_atoms a list of atom indices

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/openmmtools#285]
I came across a case where creating a DSL selection string for the atoms I need to restrain is quite a pain. I'm thinking of making [`forcefactories.restrain_atoms()`](https://github.com/choderalab/openmmtools/blob/master/openmmtools/forcefactories.py#L89) a little more flexible by changing its signature from
```python
def restrain_atoms(..., topology, atoms_dsl,...):
```
to
```python
def restrain_atoms(..., restrained_atoms, ...):
```
where `restrained_atoms` is a simple list of atom indices. Any objections to this?

**Comment by Lnaden** [comment]
Is it possible to support both through a Keyword feature so instead you would have a call of
```python
def restrain_atoms(..., restrained_atoms=None, topology=None, atoms_dsl=None, ...):
```
where it accepts either a `restrained_atoms` list OR a `topology` and `atoms_dsl`? Probably need to do some cleanup of the call. I think having the dsl string is still very helpful for atom selection and we should not rely solely on the integer list, which is why you put in the dsl option in the first place, is it not?

**Comment by Lnaden** [comment]
Nd raise an error if both are selected or not enough criteria are provided to the topopogy/dsl

**Comment by andrrizzi** [comment]
Also, currently the function centers the positions of all atoms that match the DSL string `protein`, but this doesn't work for host-guest systems. Would computing the centroid of the `restrained_atoms` alone suffice for the `MonteCarloBarostat` to not give problems? Alternatively, we'll have to add a separate `receptor_atoms` argument.

**Comment by andrrizzi** [comment]
> where it accepts either a `restrained_atoms` list OR a `topology` and `atoms_dsl`?

I don't generally like having multiple redundant arguments, but yes we can in principle. I originally wrote it with those two arguments because I didn't think of a case in which they would cause problems (like this one).

**Comment by Lnaden** [comment]
I agree I don't like the multiple calls, but both types of arguments have problems. What about if there were two functions which handled preprocessing of the input before passing to an internal function of common action like

```python
def restrain_atoms_by_dsl(..., topology, atoms_dsl, ...):
    # Stuff
    return _restrain_atoms(unified_selection,...)

def restrain_atoms_by_indices(..., atom_indices, ...):
    # Stuff
    return _restrain_atoms(unified_selection,...)

def _restrain_atoms(..., unified_selection, ...,)
```

**Comment by andrrizzi** [comment]
I like that better (I hate not having proper overloading in Python)! Although, I'd do only 2 methods
```python
def restrain_atoms_by_dsl(..., topology, atoms_dsl, ...):
    restrained_atoms = topology.select(atoms_dsl).list()
    return restrain_atoms(...,restrained_atoms,...)

def restrain_atoms(..., atom_indices, ...):
    # Stuff
```

**Comment by Lnaden** [comment]
Better. I really think having both functionalities, or at bare minimum a DSL processing is much better from a user standpoint than just atom indices.
