### ISSUE TITLE
CustomExternalForce should use periodicdistance to avoid major artifacts when heavy atoms are restrained to fixed points in space

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#310]
cc: https://github.com/pandegroup/openmm/issues/1854#issuecomment-346202857

In order to avoid major artifacts when using restraints to fixed points in space via `CustomExternalForce` (in [`restrain_atoms`](https://github.com/choderalab/openmmtools/blob/f50f0844b28106978973e6374613bc8d24a3c4b9/openmmtools/forcefactories.py#L101)), for periodic systems, we should replace
```python
restraint_force = mm.CustomExternalForce('(K/2)*((x-x0)^2 + (y-y0)^2 + (z-z0)^2)')
```
with
```python
restraint_force = mm.CustomExternalForce('(K/2)*periodicdistance(x, y, z, x0, y0, z0)^2')
```
as suggested in [this comment](https://github.com/pandegroup/openmm/issues/1854#issuecomment-346493353).

The relevant code is [here](https://github.com/choderalab/openmmtools/blob/f50f0844b28106978973e6374613bc8d24a3c4b9/openmmtools/forcefactories.py#L158).

**Comment by jchodera** [comment]
We should be careful to not use `periodicdistance` if the system is not periodic. See [this clarification](https://github.com/pandegroup/openmm/issues/1854#issuecomment-346893115).

**Comment by Lnaden** [comment]
So it sounds like we should have two `CustomExternalForce`s on the `ThermodynamicState` object which yields the single, correct `Force` if a `Barostat` is applied or not

**Comment by jchodera** [comment]
No, that doesn't seem right. 

My understanding is that, when adding the restraining force, we should select the energy expression for `CustomExternalForce` depending on whether [`System.usesPeriodicBoundaryConditions()`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.System.html#simtk.openmm.openmm.System.usesPeriodicBoundaryConditions) is `True` or `False`.
