### ISSUE TITLE
Use classes for integrators?

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/openmmtools#34]
It might be cute to use classes instead of functions, so that we can use inheritance to do further customizations.  This is not unprecedented, as Peter's RESPA integrator does this.

This would also let us write decorators that calculate various convergence statistics for monitoring.  Also, we could use member functions to help with tuning various mcmc parameters.

**Comment by jchodera** [comment]
Good idea.  I've thought about this in earlier passes through this code.

Can you point me to Peter's RESPA integrator?  Is that pure python?

**Comment by kyleabeauchamp** [comment]
https://simtk.org/svn/pyopenmm/trunk/simtk/pyopenmm/extras/respa.py

We should just copy this into openmmtools, so that we can actually use and test it.

**Comment by jchodera** [comment]
Will do.

I hadn't realized you could subclass swig-wrapped C++ classes like `CustomIntegrator`.  Will do this for the others in a PR.

**Comment by kyleabeauchamp** [comment]
Done in #36
