### ISSUE TITLE
How to do MC simulations with proteins and add custom energy functions?

### ISSUE THREAD

**Issue by changephilip** [choderalab/openmmtools#347]
Hello！
I am new to openmmtools.
When i run **testsystems**._AlanlineDipeptideVacuum_ simulation to learn MC simulation of proteins,
the **MCsampler** docs say that only need to set **MCmover**, and run "**sampler**._run_(iter=100..)
However, I don't know whether if I can use my **customed energy function** to replace the default one.
The second problem is  how to **save and check my simulation result**?
In openmm, i can add a reporter to **simulation** object and save the result structure.
I found no information about it in openmmtools .
More tutorials about how to run a MC simulation are welcomed.

**Comment by andrrizzi** [comment]
Hi @changephilip . You'll have to build your OpenMM system using OpenMM custom forces if you want a different energy function and pass that system to the `ThermodynamicState` object (see [OpenMM's docs](http://docs.openmm.org/latest/api-python/library.html#forces)).

Unfortunately, we don't have an integrated way of storing your simulation data in `openmmtools` yet. We're working on it. If you're interested in the trajectory, you could take a look at what MDTraj has to offer.
