### ISSUE TITLE
Compatibility of AlchemicalState with new changes in OpenMM

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/openmmtools#359]
New changes in OpenMM (the addition of offsets to have exact PME) have resulted in the creation of a global parameter that is not recognized by `AlchemicalState`.

Basically, the normal `NonbondedForce` now has a global parameter (but may actually have many global parameters? @jchodera perhaps you could inform here), but it is not exposed in the canonical way. As a result, attempting to apply an `AlchemicalState` to one of these new systems results in an error. 

I _think_ that changing [this method](https://github.com/choderalab/openmmtools/blob/master/openmmtools/alchemy.py#L746-L768) might be all that's needed, but I am not sure. I will take a stab at it to see what happens, but in the meantime please inform if there are any other potential pitfalls.

**Comment by pgrinaway** [comment]
Actually, I'm not really sure what the right way to do this is. It looks like the `AlchemicalState` applies itself to a system by setting default parameter values. But that is not how the new API works--in that case, the parameter is only changed by `context.setParameter`. I could be wrong about this, though...

**Comment by pgrinaway** [comment]
I guess what I might suggest is allowing `apply_to_system` to proceed without doing anything, but then setting the parameter value with `apply_to_context`? In other words, this parameter, unlike the others, will be only stored in the `AlchemicalState`.

**Comment by jchodera** [comment]
If it would make sense to extend the NonbondedForce API to allow querying of the global parameters like other forces, I propose we suggest this improvement on the OpenMM issue tracker so we can simplify things.

**Comment by andrrizzi** [comment]
I'll have to look into it, but I think the main problem is that `AlchemicalState` needs to know how to set the parameter in the system to create a _standard system_ and take advantage of the compatibility concept.

I don't think `AlchemicalState.apply_to_context()` tries to modify the system unless you want to change the charges through `updateParametersInContext()`.

> I propose we suggest this improvement on the OpenMM issue tracker so we can simplify things

This would indeed make things easier. If this is urgent, let me know and we can work to implement a special case.

**Comment by jchodera** [comment]
Hopefully we can get https://github.com/pandegroup/openmm/issues/2117 implemented quickly and no changes in `openmmtools` will be needed.

**Comment by pgrinaway** [comment]
Since it doesn't look like this will be changed favorably in OpenMM, could we make a subclass of `NonbondedForce` that just adds the requisite API?

**Comment by andrrizzi** [comment]
This was implemented in pandegroup/openmm#2119 .
