### ISSUE TITLE
Dropping Python 2 support

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/openmmtools#361]
We are thinking of dropping Python 2 support soon.

@dwhswenson, @jhprinz, I think `openpathsampling` still supports Python 2 and relies on some utility functions here. Would it be a problem if the `openmmtools 0.16` release will drop it?

Should we wait to drop it in `openmmtools 0.17` and raise a deprecation warning on import in `openmmtools 0.16` instead?

**Comment by dwhswenson** [comment]
I don’t think this will cause any problems for us. At least, not immediately, as long as the last 2.7-compatible release of OpenMMTools remains installable. It just means that under 2.7 we’ll use a different version of OpenMMTools than under 3.x.

The only possible problem is if the OpenMMTools API changes later in one of the corners we use. The most likely candidate for that is in integrator serialization. (We recommend using the integrators from OpenMMTools, and therefore use parts of `RestorableOpenMMObject`.) Other than that, I think we just have a few integrations that enable us to quickly use a `TestSystem` to set up OPS (sometimes used in our test suite). That API seems pretty stable. 

Anyway, even if the API changes, it just requires a bit of compatibility code on our part. Maybe I could make a PR here to add a test that mocks the current functionality of OPS’s use of OpenMMTools? Then you wouldn’t have to worry about these things — you’d have a test that would give you a heads-up if you’re changing something that would affect OPS (and if you then told us, we could make the fix on our side.)

Thanks for giving us the warning!

**Comment by andrrizzi** [comment]
Great! Now that I've generalized the `RestorableOpenMMObject` to forces too, I believe that part will be pretty stable as well.

Is there any objection in dropping Python 2.7 support in 0.16 then?

**Comment by dwhswenson** [comment]
> Is there any objection in dropping Python 2.7 support in 0.16 then?

No objection from me! (Not sure if the question was for me or for the OpenMMTools team.)

**Comment by andrrizzi** [comment]
Python 2 support was dropped in #380.
