### ISSUE TITLE
Unused parameter `flexibleConstraints` in testsystems

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/openmmtools#38]
A simple search for `flexibleConstraints` in testsystems suggests that this parameter is never actually used anywhere--it's present only in the constructor function header and nowhere else.

**Comment by kyleabeauchamp** [comment]
Fixed in #39

**Comment by jchodera** [comment]
To give context: This was used before we had a minimizer inside of OpenMM, and needed to use something like LBFGS from `scipy` that didn't know about constraints.
