### ISSUE TITLE
Possible strange behavior with ContextCache

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/openmmtools#383]
Using the `ContextCache` context, @ivyzhang999 and I have noticed that the energies of some components of the potential are nan (though oddly the total is not). If we create a new context using the same system and positions, we get very typical values for the potential components. 

However, as I was writing this, we discovered that using the `DummyContextCache` doesn't alleviate the strange NaN behavior.

**Comment by ivyzhang999** [comment]
Example of output: 

components from original context: 
[('HarmonicBondForce', Quantity(value=35639.035228400004, unit=kilojoule/mole)), ('HarmonicAngleForce', Quantity(value=nan, unit=kilojoule/mole)), ('PeriodicTorsionForce', Quantity(value=442.3324799999965, unit=kilojoule/mole)), ('NonbondedForce', Quantity(value=nan, unit=kilojoule/mole)), ('AndersenThermostat', Quantity(value=0.0, unit=kilojoule/mole))]

components from new context (created using the same system and positions):
[('HarmonicBondForce', Quantity(value=17.624139811426193, unit=kilojoule/mole)), ('HarmonicAngleForce', Quantity(value=55.34692154413624, unit=kilojoule/mole)), ('PeriodicTorsionForce', Quantity(value=47.54061243684281, unit=kilojoule/mole)), ('NonbondedForce', Quantity(value=-199.4889130169615, unit=kilojoule/mole)), ('AndersenThermostat', Quantity(value=0.0, unit=kilojoule/mole))]

**Comment by pgrinaway** [comment]
Nevermind, I think this was a mistake on our end.
