### ISSUE TITLE
Critical bugfix release

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#425]
Now that https://github.com/choderalab/openmmtools/pull/423 has been merged, we should get a critical bugfix out, since anyone who upgrades `scipy` will likely run into trouble otherwise.

**Comment by andrrizzi** [comment]
Sounds good. I can push a 0.18.2 release today or tomorrow if there are no objections.

**Comment by jchodera** [comment]
No objections, @andrrizzi! Please go ahead when you get a chance!

**Comment by andrrizzi** [comment]
On it!

**Comment by andrrizzi** [comment]
0.18.2 files have been pushed on Anaconda.
