### ISSUE TITLE
Barostat support in ThermodynamicState

### ISSUE THREAD

**Issue by Olllom** [choderalab/openmmtools#436]
Hi,

I would like to use the replica exchange facility for systems that have a `MonteCarloAnisotropicBarostat` or a `MonteCarloMembraneBarostat`.

Right now `ThermodynamicState` only supports the `MonteCarloBarostat` although it looks to me like upgrading it to the other barostat classes should be fairly straightforward.

From what I see in the code the anisotropic barostat should be **supported without any changes** to the code (other than adding it to the list of supported barostats). The `MonteCarloBarostat` can remain the go-to class if the system does not have a barostat upon initialization, but if an anisotropic barostat exists, it could get handled exactly as the isotropic barostat. Or am I missing something? 

Same for a membrane barostat with zero surface tension. 

It looks like the only non-trivial change would be to support surface tensions (getters, setters, keyword arguments in the constructor, and the gamma*A term in the reduced energy).

For now we could just check that the surface tension is zero when initializing the ThermodynamicState and add support for non-zero surface tensions later. 

What do you think?

**Comment by Olllom** [comment]
* anisotropic barostat with equal pressure in all dimensions that are scaled

**Comment by andrrizzi** [comment]
This is a very welcomed feature, thank you! I'll review the PR shortly.
