### ISSUE TITLE
Option to create custom barostats?

### ISSUE THREAD

**Issue by EqualAPriori** [choderalab/openmmtools#447]
Hi all, thank you for the really interesting work here. I have been studying the tutorials and it looks like there is a nice interface to write general MonteCarlo moves. I wanted to check if I will be able to write custom barostats with the current openmmtools features. 

First, my use case (which is admittedly non-standard, I'm experimenting): I want to apply some kind of external potential field on my system, that depends on box size. At the same time, I also want to allow for barostat moves, which will necessarily change the box and the external potential. I don't think the current openmm barostat is able to change the global parameters of an applied external force while it is doing its checks on the energy. As such, currently I've been barostating manually (see post below) -- I run the simulation for a short interval, then perform the barostat moves and forcefield modifications via the python interface.

Now, if I want to do this all in openmm tools, my current understanding is that:
1. the openmmtools MonteCarloBarostat function is designed for use with native openmm barostats, and thus
2. I will have to create a new class modeled after BaseMetropolizedMove that explicitly handles the proposed box changes, modifying the external force field and proposing new perturbed positions
3. If I inherit from BaseMetropolizedMove then I may have to write a new composed, thermodynamic state to modify the force field parameters accordingly, because BaseMetropolizedMove handles all the context-setting and energy calculations, not the move proposal

Lastly, I was wondering if barostating using openmmtools would be any faster than barostating manually via the python interface of openmm? It seems like everything would be handled through python still, but maybe there is special magic in openmm that offers speed (from my assumption that custom openmmtools integrators are fast as the native openmm integrators).

Thank you for your advice!

**Comment by EqualAPriori** [comment]
A sample pseudocode of my current barostating procedure:
`
    boxsizes = np.zeros([nblocks,3])
    TotalAcceptances = 0
    TotalMCMoves = 0
    for iblock in range(0,nblocks):
        logger.info("Starting block {}".format(iblock))
        start = time.time()
        simulation.step(barostatfreq)
        end = time.time()
        logger.info('Took {} seconds for block {}'.format(end-start,iblock))

        # === barostat move ===
        if args.tension > 0:
            logger.info('=== Attempting area change ===')
            #--- Assumes args.tension in units of bar*nm ---
            kBT = u.AVOGADRO_CONSTANT_NA * u.BOLTZMANN_CONSTANT_kB * args.temperature * u.kelvin
            tension = args.tension*u.bar*u.nanometer*u.AVOGADRO_CONSTANT_NA

            #--- Set up ---
            Eold = simulation.context.getState(getEnergy=True).getPotentialEnergy()
            logger.info('... Current energy: {}'.format( Eold.value_in_unit(u.kilojoule_per_mole) ))
            if np.random.random_sample() < 0.5:
                logger.info('... proposing to shrink area by {}...'.format(scaling))
                tmpf = 1/scaling
            else:
                logger.info('... proposing to expand area by {}...'.format(scaling))
                tmpf = scaling

            scaleNormal = 1/tmpf
            scaleTangent = tmpf**0.5
            
            #--- actually scale box ---
            #===> code to change the box size --> keep box volume same for area changes, so don't have those terms in reduced potential
            #===> code to determine the new scaled positions
            simulation.context.setPositions(newpos)
            #===> code to change the force field to be commensurate with box size
            Enew = simulation.context.getState(getEnergy=True).getPotentialEnergy()

            #--- Monte Carlo Acceptance/Rejection ---
            w = Enew - Eold - tension*deltaArea + (Non-Standard Area Penalties as Desired)
            betaw = w/kBT
            logger.info('... MC transition energy: {}'.format(betaw))
            if betaw > 0 and np.random.random_sample() > np.exp(-betaw):
                #Reject the step
                logger.info('... Rejecting Step')
                #---> reset box size, reset positions, reset force field
            else:
                #Accept step
                logger.info('... Accepting Step')
                TotalAcceptances = TotalAcceptances + 1
            TotalMCMoves += 1
`

**Comment by andrrizzi** [comment]
Hi @EqualAPriori. I think that should be very possible within the MCMC framework, and the steps you outlined look correct to me.

You probably have done it already, but I'd investigate first if there's a way to implement that through a custom integrator or a custom force. The MCMCMove won't be more efficient than the Python implementation (save maybe a couple of minor optimizations), but if you manage to implement it as a custom OpenMM object, OpenMM will compile the code for GPU, which may give you a good speedup.

**Comment by EqualAPriori** [comment]
Thanks for the feedback -- good to know that the MCMCMove won't be that much more efficient. I've thought of doing it as an integrator, but there were a lot of mechanics that seemed daunting: I was 1) uncertain how to make the integrator potentially change the global variable of another force field; 2) how to stage integrators to only apply at intervals/frequencies. Although for speed purposes it does seem like implementing a Nose-Hoover barostat integrator would be the best way, provided the integrator function lets us modify other force fields as we go. I'm also unaware of CustomBarostat forces in OpenMM -- if you happen to know of any good directions, do let me know!

Related -- do you know if it is possible to tie a global variable of an OpenMM custom force to a context parameter (i.e. box size)?

**Comment by andrrizzi** [comment]
Sorry for the late answer. I must have missed the notification on your reply.

> do you know if it is possible to tie a global variable of an OpenMM custom force to a context parameter (i.e. box size)?

A global variable of an OpenMM custom force becomes a context parameter (i.e. you can access all the global variables with `context.GetParameters()`, but I'm not aware of any mechanism that you can use to tie them directly to the box size.

Personally, I think the MCMCMove design should be faster to implement so it should be good for prototyping. If you're interested in trying to increment the performance with a custom integrator, I'd suggest you ask on the OpenMM issue tracker as you're probably going to receive better suggestions on the topic. It's not guaranteed that it'll improve performance though because certain operations in custom integrators that are not parallelizable are performed on the CPU anyway, which may result in little benefits that are not worth the extra implementation and maintenance efforts.

**Comment by jchodera** [comment]
> A global variable of an OpenMM custom force becomes a context parameter (i.e. you can access all the global variables with context.GetParameters(), but I'm not aware of any mechanism that you can use to tie them directly to the box size.

In principle, we could ask for box vectors (and their energy gradients) to be exposed within `CustomIntegrator`.

**Comment by EqualAPriori** [comment]
Thanks for all the insights! I've decided to prototype in just python
first. Right now I restrict by barostat move frequency to about every 1000
steps (instead of the typical 25 steps), which is acceptably fast enough
while maintaining a reasonable number of barostat moves over the course of
the simulation lengths that I have. If this is not fast enough then I'll
seek to go with the CustomIntegrator route.

**Comment by andrrizzi** [comment]
Great! Closing this to keep the issue tracker clean, but feel free to re-open.
