### ISSUE TITLE
Travis tests are failing

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#452]
Travis tests have started to fail. It looks like this is due to a [string-formatting issue](https://travis-ci.org/choderalab/openmmtools/jobs/614470159#L3230-L3239):
```
======================================================================
ERROR: Testing reference/alchemical overlap for no alchemical dispersion LennardJonesFluid with dispersion correction, annihilated sterics
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/choderalab/openmmtools/openmmtools/tests/test_alchemy.py", line 1164, in overlap_check
    'du mean {:.3f} kT stddev {:.3f} kT').format(DeltaF, dDeltaF, Neff, g, du_n.mean(), du_n.std())
ValueError: Unknown format code 'f' for object of type 'str'
-------------------- >> begin captured logging << --------------------
```

**Comment by jchodera** [comment]
This is super weird---no idea why this might be happening.

Maybe we should change from `.format()` to [f-strings](https://realpython.com/python-f-strings/)?

**Comment by djhuggins** [comment]
Hi John. I found a similar error which I tracked down to the latest version of pymbar returning a string rather than an array for (in my case) Deltaf_ij. May be the problem here?

**Comment by jchodera** [comment]
@Lnaden @mrshirts @andrrizzi : Any idea how or why the output of pymbar might have suddenly changed?

**Comment by Lnaden** [comment]
What version of PyMBAR are you running, @djhuggins?

**Comment by djhuggins** [comment]
@Lnaden I was using pymbar 3.0.4 when this problem occurred. I rolled back to pymbar 3.0.3 and there was no error.  

To confirm the error, I was getting "TypeError: string indices must be integers" when attempting to access elements of Deltaf_ij.

**Comment by jchodera** [comment]
@lnaden: The travis tests recently started failing for `openmmtools` with these weird errors above.

Could something have gone wrong in the [pymbar 3.0.4 release](https://github.com/choderalab/pymbar/releases/tag/3.0.4)?

**Comment by jchodera** [comment]
@andrrizzi @jaimergp: I'm digging into this now to figure out what's going on, but we'll want to sort these issues out on Monday since it is impacting all of our free energy ecosystem.

**Comment by jaimergp** [comment]
Took a quick look at the diff between `3.0.3` and `3.0.4`. Some observations:

* Looks like `3.0.4` [uses a `dict` to store the results](https://github.com/choderalab/pymbar/compare/3.0.3...3.0.4#diff-2f68bad712f6798ec69aced2640b2215R218) and returns that. 
* `3.0.3` returned [either a tuple or a single value](https://github.com/choderalab/pymbar/compare/3.0.3...3.0.4#diff-2f68bad712f6798ec69aced2640b2215L376).
* I agree that having a `dict` returned is a better API so there is type consistency across different options.
* However, if old code relied on iteration to get the values, that same code will now iterate over the keys of the dict, which will return `str` objects, not the numeric values. Could that be the reason?

**Comment by jaimergp** [comment]
Yes, I think that could be indeed the reason.

This is the [test code that is failing](https://github.com/choderalab/openmmtools/blob/master/openmmtools/tests/test_alchemy.py#L1159). As suspected, this will unpack the dictionary keys, instead of the values. That's why you get `str` objects:

```
In [2]: d = {'a': 0, 'b': 1}

In [3]: x, y = d

In [4]: x
Out[4]: 'a'

In [5]: y
Out[5]: 'b'

```

**Comment by jchodera** [comment]
@jaimergp : Thanks for catching this!

Yikes! There's no way we should have broken the API in a non-backward-compatible manner in a minor bugfix release! I'll create an issue on the `pymbar` issue tracker and we can revert that ASAP.
