### ISSUE TITLE
Conda Installation Issue

### ISSUE THREAD

**Issue by gideonsimpson** [choderalab/openmmtools#458]
I was doing a fresh install of anaconda with Python 3 on a MacOS 10.14.6, and I found that while I had no problem installing openmm itself,
```
conda install -c omnia openmmtools
```
resulted in a compatibility issue that anaconda could not resolve.  I found I had this problem with the 2019.03, 2019.07, and 2019.10 distributions of anaconda.

**Comment by jchodera** [comment]
You need to include both `conda-forge` and `omnia` channels:
```bash
conda install -c omnia -c conda-forge openmmtools
```

**Comment by gideonsimpson** [comment]
Thanks.  Maybe you guys could update https://anaconda.org/omnia/openmmtools to reflect that requirement?

**Comment by Lnaden** [comment]
We have no control over that install string on anaconda, its auto-generated when we upload the package. The best we can do is have it on our [install instructions](https://openmmtools.readthedocs.io/en/latest/installation.html). Its a bit confusing so I apologize for that, its just the way anaconda reports its packages.

**Comment by jaimergp** [comment]
Maybe we can link to the documentation in the Anaconda description field?

**Comment by jchodera** [comment]
Our hope for this is to migrate `openmmtools` and other `omnia` packages over to `conda-forge` as soon as possible, but we're still working with @peastman on establishing a route to do this for the `openmm` dependency.

**Comment by ijpulidos** [comment]
I believe `openmmtools` and `openmm` have now `conda-forge`  as primary source repo. Maybe this issue can be closed now?

**Comment by jchodera** [comment]
Yes, thanks!
