### ISSUE TITLE
ReplicaExchangeSampler example not working

### ISSUE THREAD

**Issue by markahix** [choderalab/openmmtools#461]
[Example for ReplicaExchangeSampler](https://openmmtools.readthedocs.io/en/0.18.1/api/generated/openmmtools.multistate.ReplicaExchangeSampler.html), when followed exactly, produces the following error:

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-19-3603b9dbbdff> in <module>
      1 move = mcmc.GHMCMove(timestep=2.0*unit.femtoseconds, n_steps=50)
----> 2 simulation = ReplicaExchangeSampler(mcmc_moves=move, number_of_iterations=2)
NameError: name 'ReplicaExchangeSampler' is not defined

---------------------------------------------------------------------------

I've checked and double-checked to ensure the installation is correct, and I'm at a loss.  I also can't seem to find anyone else on the internet that's had the same issue.

**Comment by hannahbrucemacdonald** [comment]
Hey!


Does

`from openmmtools.multistate import ReplicaExchangeSampler`

work without complaint? Otherwise, could you let me know which version of openmmtools you're running?

either using `conda list openmmtools` in the command line, or in python

>>>import openmmtools
openmmtools.__version__

**Comment by Lnaden** [comment]
The examples as part of the class docstring are not exactly complete in the imports, specifically in importing the class itself. They implicitly assume you have already imported the class into the namespace. To make the example work, you have to have the line
```python
from openmmtools.multistate import ReplicaExchangeSampler
```
somewhere before the example or in the imports. A PR to update the example would be very welcome (all of the samplers would need a similar string)

**Comment by markahix** [comment]
> Hey!
> 
> Does
> 
> `from openmmtools.multistate import ReplicaExchangeSampler`
> 
> work without complaint? Otherwise, could you let me know which version of openmmtools you're running?
> 
> either using `conda list openmmtools` in the command line, or in python
> 
> `import openmmtools`
> `openmmtools.__version__`

Using the import line above, I get the following new error:

ModuleNotFoundError: No module named 'openmmtools.multistate'

From "conda list openmmtools" I get:

# packages in environment at /home/mark/anaconda3:
#
# Name                    Version                   Build  Channel
openmmtools               0.17.0                   py36_0    omnia


Now that I'm seeing this, I'm thinking I need to use a different channel.  Is conda-forge updated to 18?

**Comment by markahix** [comment]
I've tried uninstalling the omnia version and using the conda-forge version, same result.  I've also cloned this repository and installed it locally, giving me version 0.19, and combining that with the import line in the first comment by @hannahbrucemacdonald seems to have gotten me past that issue.

Thanks all!
