### ISSUE TITLE
Add standard JAC benchmark systesm to testsystems

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#47]
It would be useful to have the standard JAC benchmark systems in `openmmtools.testsystems`, with the DHFR system likely being most valuable.

The AMBER version of the input files is available here, but the `prmtop` files are unfortunately only available in the "old" `prmtop` format:
http://ambermd.org/Amber14_Benchmark_Suite.tar.bz2

I believe the current AMBER `prmtop` loader only reads the "new" `prmtop` file formats, so we would need to either convert these to new format (using ParmEd from @swails?), upgrade the `prmtop` reader to read the "old" style files, or find the CHARMM version of these files and try out the CHARMM loader.

**Comment by kyleabeauchamp** [comment]
I believe this works:

```
import chemistry
prmtop = chemistry.load_file("./prmtop")
prmtop.write_parm("./new.prmtop")
```

**Comment by kyleabeauchamp** [comment]
Looks like AMBER doesn't have a GB version of this benchmark, though.  

For GB, we could possible use the files already included in openmm: 

```
examples/benchmark.py
5dfr_minimized.pdb
5dfr_solv-cube_equil.pdb
```

**Comment by jchodera** [comment]
Is `chemistry` from ParmEd?

**Comment by swails** [comment]
Why not just use ParmEd for all of it?

```Python
import chemistry
from simtk.openmm import app
from simtk import openmm as mm

prmtop = chemistry.load_file('./prmtop')
system = prmtop.createSystem(nonbondedMethod=app.PME, nonbondedCutoff=8*u.angstroms)
```

**Comment by swails** [comment]
> Is `chemistry` from ParmEd?

Yes.

**Comment by jchodera** [comment]
Is ParmEd now being distributed in `omnia`?  If so, we can totally do that.

**Comment by swails** [comment]
> Is ParmEd now being distributed in omnia? If so, we can totally do that.

No, but I'm not opposed to that.

**Comment by jchodera** [comment]
Alternatively, we can have a short script import the `prmtop` and export OpenMM `xml` format.

**Comment by jchodera** [comment]
> No, but I'm not opposed to that.

I think this would be great.  We would just need a conda recipe to be added to [conda-recipes](https://github.com/omnia-md/conda-recipes) via a PR.

**Comment by jchodera** [comment]
> For GB, we could possible use the files already included in openmm:

Would be good to include those versions too.

**Comment by swails** [comment]
I've never tried this before (I really have to start *using* conda more than I already have... it's quite cool).

**Comment by jchodera** [comment]
We can give you a hand, but the easiest way to get started is generally to pick a recipe for a similar project and tweak it.

Documentation for building recipes can be found [here](http://conda.pydata.org/docs/build.html).

You can start with [miniconda](http://conda.pydata.org/miniconda.html) if you don't have an anaconda installation already.  If you unpack it somewhere, it won't interfere with your existing python installation.

**Comment by kyleabeauchamp** [comment]
Yeah, we can do this during our meeting if so desired.

**Comment by jchodera** [comment]
Great to idea!

**Comment by kyleabeauchamp** [comment]
I think this is done in #50
