### ISSUE TITLE
GPU test_alchemy.py failures.

### ISSUE THREAD

**Issue by adw62** [choderalab/openmmtools#520]
Hello,

I am experiencing some test failures for OpenMMTools when using the GPU platform and was hoping I could get some help resolving them.

I have set up a test environment for OpenMMTools using a Conda environment and the YAML here: https://github.com/choderalab/openmmtools/blob/master/devtools/conda-envs/test_env.yaml which yields this environment for me: [environment.txt](https://github.com/choderalab/openmmtools/files/7187592/environment.txt)

I git clone OpenMMTools, install with pip, then run  `nosetests test_alchemy.py ` in the test directory of my clone.

On CPU this yield the following output: [cpu.txt](https://github.com/choderalab/openmmtools/files/7187614/cpu.txt)

On GPU I get many more errors about large energy differences for HostGuestExplicit with PME based tests: [gpu.txt](https://github.com/choderalab/openmmtools/files/7187625/gpu.txt)

Am I running these test correctly or am I missing something in the GPU case? Any help with this would be greatly appreciated.

For reference I'm using an Ubuntu Linux 64 machine with an RTX 2070S, Driver Version: 470.63.01, CUDA Version: 11.4, cudatoolkit=11.2.2

Thanks,
Alex

**Comment by adw62** [comment]
An update on this: 
Performing these test using OpenMM ver. 7.4.2 results in no energy errors. If I use 7.6 these errors occur again. I tested with cudatoolkit 10.1 and 11.2 (not sure if this will help?) 

I've attached here my OpenMM 7.4 and 7.6 Conda environments for reference: 
[open74.txt](https://github.com/choderalab/openmmtools/files/7197959/open74.txt)
[open76.txt](https://github.com/choderalab/openmmtools/files/7197945/open76.txt)

Could it possible that some of the CUDA code in OpenMM pertaining to the alchemical-ness of the system has changed between 7.4 and 7.6 causing this issue on GPU?

**Comment by mikemhenry** [comment]
Thanks for the issue @adw62! I will try and reproduce.

**Comment by ijpulidos** [comment]
@adw62 I was able to get some errors in the tests, but it is curious that the errors I am getting [here](https://gist.github.com/ijpulidos/596d53809cb9a6215fefedc2608211d3) are different (ignore the parmed module missing one, btw). I'm getting these using exclusively the conda-forge packages for openmmtools and openmm (nothing installed using git/pip, any special reasons why you are installing openmmtools using pip?). So, it seems to be something that changes under different conditions, probably under different GPUs. 

This test was run with CUDA 11.4 and a small nvidia quadro T500 GPU. I'll be having results using a bigger Nvidia GeForce GTX TitanX shortly, to compare with.

**Comment by jchodera** [comment]
For one of the failing tests (ideally the simplest/smallest one), can you serialize out the `System` and `State` objects to XML for us to investigate? Something like this:
```python
from simtk.openmm import XmlSerializer
with open('system.xml', 'wt') as outfile:
    outfile.write(XmlSerializer.serialize(context.getSystem()))
with open('state.xml', 'wt') as outfile:
    outfile.write(XmlSerializer.serialize(context.getState(getPositions=True, getForces=True, getEnergy=True, getParameters=True, getIntegratorParameters=True)))
```
This will make it easier for us to look at in detail, especially if we have to bring in Peter Eastman.

**Comment by ijpulidos** [comment]
I can see that the test systems that fail the energy components comparison test have using "exact PME" in common. I don't know if that rings any bells. I'll be serializing the `System` and `State` soon.

**Comment by ijpulidos** [comment]
@jchodera This is one of the systems that fails with the energy components test. The system is in XML while the state is in pickle, because I don't think OpenMM's `XmlSerializer` allows the serialization of `openmmtools.alchemy.AlchemicalState` objects.
[openmmtools-520.tar.gz](https://github.com/choderalab/openmmtools/files/7262596/openmmtools-520.tar.gz)

**Comment by jchodera** [comment]
> @jchodera This is one of the systems that fails with the energy components test. The system is in XML while the state is in pickle, because I don't think OpenMM's XmlSerializer allows the serialization of openmmtools.alchemy.AlchemicalState objects.

That's correct, but we don't necessarily need the `AlchemicalState` object to debug this---we just need the XML representation fo the pure C++ `State` object.

**Comment by adw62** [comment]
@ijpulidos That's good you can reproduce this with the Conda installs, there is no special reason I'm using pip here.

I also had a go at serializing out the `HostGuestExplicit` system with ver. 7.4 and 7.6: [sys_states.zip](https://github.com/choderalab/openmmtools/files/7266910/sys_states.zip) I can't see any material difference in the `System` the `State` is harder for me to interpret so not sure if there are clues in there.

I have noticed that the `energy_components` from the function `get_energy_components()` in `alchemy.py` are substantially different between OpenMM versions.

With the `HostGuestExplicit` system I get with 7.4:
```
OrderedDict([('unmodified CMMotionRemover', Quantity(value=0.0, unit=kilojoule/mole)), ('unmodified HarmonicBondForce', Quantity(value=347.9458923339844, unit=kilojoule/mole)), ('unmodified HarmonicAngleForce', Quantity(value=637.158203125, unit=kilojoule/mole)), ('unmodified PeriodicTorsionForce', Quantity(value=392.7203369140625, unit=kilojoule/mole)), ('unmodified NonbondedForce', Quantity(value=-53488.81566970975, unit=kilojoule/mole)), ('alchemically modified NonbondedForce for non-alchemical/alchemical sterics', Quantity(value=118.97273138044244, unit=kilojoule/mole)), ('alchemically modified NonbondedForce for alchemical/alchemical sterics', Quantity(value=-3.6006835941804947, unit=kilojoule/mole)), ('alchemically modified BondForce for alchemical/alchemical sterics exceptions', Quantity(value=55.18846130371094, unit=kilojoule/mole)), ('alchemically modified BondForce for non-alchemical/alchemical sterics exceptions', Quantity(value=0.0, unit=kilojoule/mole))])
```

and on 7.6:
```
OrderedDict([('unmodified CMMotionRemover', Quantity(value=-394920.5, unit=kilojoule/mole)), ('unmodified HarmonicBondForce', Quantity(value=-394572.5625, unit=kilojoule/mole)), ('unmodified HarmonicAngleForce', Quantity(value=-394283.34375, unit=kilojoule/mole)), ('unmodified PeriodicTorsionForce', Quantity(value=-394527.8125, unit=kilojoule/mole)), ('unmodified NonbondedForce', Quantity(value=-53488.84691970975, unit=kilojoule/mole)), ('alchemically modified NonbondedForce for non-alchemical/alchemical sterics', Quantity(value=-394801.5106060219, unit=kilojoule/mole)), ('alchemically modified NonbondedForce for alchemical/alchemical sterics', Quantity(value=-394924.08745684667, unit=kilojoule/mole)), ('alchemically modified BondForce for alchemical/alchemical sterics exceptions', Quantity(value=-394865.3125, unit=kilojoule/mole)), ('alchemically modified BondForce for non-alchemical/alchemical sterics exceptions', Quantity(value=-394920.5, unit=kilojoule/mole))])
```
Looks like there is a large addition of -394920.5 KJ/mole to all forces. I think this might be the electrostatics not being turned off correctly. 

If that's the case then `ParticleParameterOffset` which is what's used in the exact PME cases could be relevant, I'll have a look at that next.

**Comment by jchodera** [comment]
Looping in @peastman in case he has any insight as to what we should be looking for here.

**Comment by ijpulidos** [comment]
We have decided to raise an issue in the `openmm` repo with the information gathered here.

**Comment by adw62** [comment]
Okay sounds good to me. I ran some quick tests of `ParticleParameterOffset` this morning using this code:
```python
def compute_platform_energy(platform_name):
    import numpy as np
    from simtk.openmm import System, NonbondedForce, LangevinIntegrator, Platform, Context
    from simtk.unit import (elementary_charge, dalton, nanometer, kilojoule_per_mole,
                            kelvin, femtosecond, picosecond)

    system = System()
    system.addParticle(1 * dalton)
    system.addParticle(1 * dalton)

    nbforce = NonbondedForce()
    nbforce.setNonbondedMethod(4)
    nbforce.addParticle(0 * elementary_charge, 1 * nanometer, 0 * kilojoule_per_mole)
    nbforce.addParticle(0 * elementary_charge, 1 * nanometer, 0 * kilojoule_per_mole)
    system.addForce(nbforce)

    positions = [[1.5, 1.5, 1.5], [0.5, 0.5, 0.5]]*nanometer
    box_vectors = 3 * np.identity(3) * nanometer

    temperature = 300*kelvin
    timestep = 2. * femtosecond
    freq = 1/picosecond
    cutoff = 1.2 * nanometer

    value = 0.0
    nbforce.addGlobalParameter('lam_elec0', value)
    nbforce.addGlobalParameter('lam_elec1',  value)

    nbforce.addParticleParameterOffset('lam_elec0', 0, 1, 0.0, 0.0)
    nbforce.addParticleParameterOffset('lam_elec1', 1, 1, 0.0, 0.0)

    integ_eq = LangevinIntegrator(temperature, freq, timestep)
    platform = Platform.getPlatformByName(platform_name)

    context = Context(system, integ_eq, platform)
    context.setPositions(positions)
    context.setPeriodicBoxVectors(*box_vectors)

    state = context.getState(getEnergy=True, getForces=True, getPositions=True)
    energy_lam_0 = state.getPotentialEnergy()

    value = 1.0
    context.setParameter('lam_elec0', value)
    context.setParameter('lam_elec1', value)

    state = context.getState(getEnergy=True, getForces=True, getPositions=True)
    energy_lam_1 = state.getPotentialEnergy()

    return energy_lam_0, energy_lam_1

if __name__ == '__main__':
    CUDA_lam_0, CUDA_lam_1 = compute_platform_energy('CUDA')
    print('CUDA:', CUDA_lam_0, CUDA_lam_1)
    CPU_lam_0, CPU_lam_1 = compute_platform_energy('CPU')
    print('CPU:', CPU_lam_0, CPU_lam_1)
```

both OpenMM 7.4 and 7.6 give me consistent looking results of:
```
CUDA: 0.0 kJ/mol -154.2053680419922 kJ/mol
CPU: 0.0 kJ/mol -154.2053533521435 kJ/mol
```

So I am yet to find a minimal example of what is breaking here.

**Comment by adw62** [comment]
Hello,

I have run these tests again on my machine this morning using the latest OpenMM and OpenMMtools installed by conda which gives this env: [environment.txt](https://github.com/choderalab/openmmtools/files/8283290/environment.txt)

I now no longer see any of these errors on GPU. For reference I'm now using CUDA Driver Version: 510.47.03 and CUDA Version: 11.6 with RTX2070S. So I think with the latest code this is no longer an issue and I will close it now, Thanks :)

Alex
