### ISSUE TITLE
Import error on Google Colab

### ISSUE THREAD

**Issue by bcallen95** [choderalab/openmmtools#532]
Hi there! I've been trying to run the "Alchemical Free Energy Calculations" Tutorial on the OpenMM Page. When I try to import openmmtools I get the following traceback: 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-6e6b6bde0fbf> in <module>()
----> 1 import openmmtools

2 frames
/usr/local/envs/openmm/lib/python3.7/site-packages/openmmtools/__init__.py in <module>()
      6 """
      7 
----> 8 from openmmtools import testsystems, integrators, alchemy, mcmc, states, cache, utils, constants, forces, forcefactories, storage, multistate
      9 
     10 # Handle versioneer

/usr/local/envs/openmm/lib/python3.7/site-packages/openmmtools/multistate/__init__.py in <module>()
     63 
     64 from openmmtools.multistate.multistatesampler import MultiStateSampler
---> 65 from openmmtools.multistate.multistatereporter import MultiStateReporter
     66 from openmmtools.multistate.replicaexchange import ReplicaExchangeSampler, ReplicaExchangeAnalyzer
     67 from openmmtools.multistate.paralleltempering import ParallelTemperingSampler, ParallelTemperingAnalyzer

/usr/local/envs/openmm/lib/python3.7/site-packages/openmmtools/multistate/multistatereporter.py in <module>()
   1752 # ==============================================================================
   1753 
-> 1754 class _DictYamlLoader(yaml.CLoader):
   1755     """PyYAML Loader that reads !Quantity tags."""
   1756     def __init__(self, *args, **kwargs):

AttributeError: module 'yaml' has no attribute 'CLoader'

Do you have any thoughts/advice on how to go about fixing this issue? Thanks!

**Comment by bcallen95** [comment]
It appears that my environment set-up was the issue. Alternatively setting up the Conda environment (in Google Colab) in the following way appears to fix all issues (with each separate "code block" representing a separate cell): 

`!pip install -q condacolab
import condacolab
condacolab.install()`

`import condacolab
condacolab.check()`

`!mamba install -q openmmtools`

**Comment by mikemhenry** [comment]
@bcallen95 Sorry I just saw this, that error you are getting now is from `pymbar`, see this issue: https://github.com/choderalab/pymbar/issues/419
