### ISSUE TITLE
readthedocs documentation build broken

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/openmmtools#548]
The documentation builds for readthedocs are broken https://readthedocs.org/projects/openmmtools/builds/15991755/

**Comment by mikemhenry** [comment]
@jchodera when you get a chance, can you add me to the readthedocs project for openmmtools? My username is `mmh`

**Comment by mikemhenry** [comment]
Going to keep this open until I can update our RTD config on the web ui

**Comment by mikemhenry** [comment]
@jchodera when you get a chance, can you add me to the readthedocs project for openmmtools? My username is mmh

**Comment by jchodera** [comment]
@mikemhenry : Apologies for missing this earlier! Just added you.

Perhaps we want to migrate this to be hosted by GitHub Pages instead?

**Comment by mikemhenry** [comment]
No worries! I honestly am not sure about switching to github pages, it will make some problems go away, like access control, but create new ones, like RTD does some fancy stuff to make the search work really well. I will look into it!

**Comment by mikemhenry** [comment]
This is fixed now, but the documentation points to the main branch. I prefer to have it point to the latest release, which we will do at the next release.

**Comment by mikemhenry** [comment]
Now the default is to point to stable.
