### ISSUE TITLE
Codeclimate broken 

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/openmmtools#549]
I guess the change to `main` for the main branch messed up the `codeclimate` check. I think this has to be changed from the `codeclimate` side of things.

_Originally posted by @ijpulidos in https://github.com/choderalab/openmmtools/issues/547#issuecomment-1039575300_

**Comment by mikemhenry** [comment]
Until we figure this out, I removed code climate as a required check

**Comment by mikemhenry** [comment]
I've fixed it by setting the default branch to main, but do we want to keep codeclimate?
Is this something you think is useful @jchodera ? There are a lot of tools like this and if we want something like it, we should look at the different options and settle on one that we use on all our repos.

**Comment by jchodera** [comment]
@mikemhenry : Can you check with the OpenFF devs on what they feel is the best practice here?
I'm all for standardizing this across our community here.

**Comment by mikemhenry** [comment]
Removed code climate and will replace with a linter
