### ISSUE TITLE
Importing multistate samplers modifies behavior of global context cache

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#558]
[This line](https://github.com/choderalab/perses/blob/main/perses/samplers/multistate.py#L10) causes the global context cache behavior to change in an unexpected way. I don't think we should be doing this.

This might merit a bugfix release.

cc https://github.com/choderalab/perses/issues/963

**Comment by ijpulidos** [comment]
Not sure if I am missing something, but this seems to be related exclusively to `perses`, isn't it? 

Or is it that we want users not to be able to change the global context cache behavior this way? 

That said, we might want to check if the global context cache behavior/platform is getting changed inside the `openmmtools` code base as well.

**Comment by mikemhenry** [comment]
Just as a reminder, we want to do what we did in perses here, which is to make sure that we don't have any places where we create a global context cache except here https://github.com/choderalab/openmmtools/blob/main/openmmtools/cache.py#L791

**Comment by ijpulidos** [comment]
As far as I can see there are no cases in `openmmtools` code base that change the behavior of the global context cache on imports. I am closing this one, feel free to reopen if you think I have missed something.
