### ISSUE TITLE
MultistateSampler - make iteration logging info level instead of debug?

### ISSUE THREAD

**Issue by IAlibay** [choderalab/openmmtools#584]
Discussing things with @mikemhenry today, it would be quite useful if we could get a general sense of run progression for MultistateSampler derived classes without getting all the debug information that usually comes along with it.

I am specifically referring to the following two logging events:

https://github.com/choderalab/openmmtools/blob/main/openmmtools/multistate/multistatesampler.py#L683

https://github.com/choderalab/openmmtools/blob/main/openmmtools/multistate/multistatesampler.py#L770

Alternatively something like an optional progress bar (tqdm? extra verbose argument for `run`?) would be really useful (and possibly less noisy than dealing with logger outputs).

**Comment by ijpulidos** [comment]
This sounds like something we definitely should improve. Thanks for the feedback! I don't know if @mikemhenry is already working on this, but I'm happy to give this a try, probably some day next week if it isn't that urgent.
