### ISSUE TITLE
Don't use online analysis to set offline analysis matrix dim

### ISSUE THREAD

**Issue by mikemhenry** [choderalab/openmmtools#592]
We want to make sure the `_offline_analysis` works. `_online_analysis` is experimental and can be neglected for now. We need to make sure the matrix/array dimensions include the endstates for the offline analysis.

**Comment by zhang-ivy** [comment]
I think we had discussed that this can be part of the next milestone, actually.

**Comment by mikemhenry** [comment]
Yes I made this issue as we were talking about it, I've bumped it!

**Comment by zhang-ivy** [comment]
>We need to make sure the matrix/array dimensions include the endstates for the offline analysis.

Just going to elaborate on this. We basically want to avoid initializing `initial_f_k` (in offline analysis) with the `self._last_mbar_f_k` used for online analysis. 

Going to assign this to @ijpulidos , but we can work together on this if needed.

**Comment by zhang-ivy** [comment]
We may also want to add to the docstring an explanation of online vs offline analysis -- i.e. both compute the free energies, but online is a more a crude estimate.

**Comment by zhang-ivy** [comment]
We'll also want to open an issue concerning adapting the online analysis to include unsampled endstates.

**Comment by zhang-ivy** [comment]
Note that we may also want to consider opening an issue for renaming `self.online_analysis_interval` to `self.offline_analysis_interval`

**Comment by ijpulidos** [comment]
> Note that we may also want to consider opening an issue for renaming `self.online_analysis_interval` to `self.offline_analysis_interval`

Yes, I think this is already a `TODO` in the code, but I'll be opening an issue for this. The problem with this change is that it could break backwards compatibility (which we'd probably have to anyways, at some point).
