### ISSUE TITLE
MultiStateSampler fails to delete properly when resuming the simulation

### ISSUE THREAD

**Issue by zhang-ivy** [choderalab/openmmtools#597]
When I resume a repex simulation, everything runs ok until the end of the script, when it tries to delete the `MultiStateSampler`: 
```
DEBUG:openmmtools.multistate.multistatesampler:Iteration took 0.875s.
DEBUG:openmmtools.multistate.multistatesampler:Estimated completion in 0:00:00, at 2022-Jun-23-10:47:34 (consuming total wall clock time 1:13:48.511895).
Exception ignored in: <function MultiStateSampler.__del__ at 0x2abd9e1314c0>
Traceback (most recent call last):
  File "/home/zhangi/miniconda3/envs/openmm-dev/lib/python3.9/site-packages/openmmtools-0.21.3+8.gc749908-py3.9.egg/openmmtools/multistate/multistatesampler.py", line 830, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function MultiStateSampler.__del__ at 0x2b113eda44c0>
Traceback (most recent call last):
  File "/home/zhangi/miniconda3/envs/openmm-dev/lib/python3.9/site-packages/openmmtools-0.21.3+8.gc749908-py3.9.egg/openmmtools/multistate/multistatesampler.py", line 830, in __del__
TypeError: 'NoneType' object is not callable
```

This only happens when I resume a simulation (not when I start a simulation from scratch). 

I am attaching an example for ALA->THR dipeptide in vacuum. If you want to try to reproduce the error, you'll need to run the  script with total_iterations > 5000 (since the nc files already have 5000 iterations completed).
[resume_bug.zip](https://github.com/choderalab/openmmtools/files/8968614/resume_bug.zip)

**Comment by ijpulidos** [comment]
@zhang-ivy Thanks for looking into this. It sounds like the `nc` file might not be getting properly closed after being read. What surprises me is that it only happens when resuming the simulation, so you are right that the problem should be related to the `from_storage` method. 

I will be taking a closer look into this, and let you know what I find, thanks again for the feedback.

**Comment by ijpulidos** [comment]
@zhang-ivy I tried using `MultiStateSampler` directly and I cannot reproduce the issue (I'm attaching the code to this comment), that makes me think it might be something on the `perses` side with the `HybridRepexSampler` or the `HybridCompatibilityMixin` class. If you want to try my code you should just run the `597-multisampler-create.py` first, and then just the `597-multisampler-resume.py`, in case you want to test this yourself.

On the other hand. Can you share the versions you are using for OpenMM? I keep getting `openmm.OpenMMException: Unsupported version number`, I believe you are probably using the dev version or a custom one. You can also just share the code you are using to generate the `.nc` files and I can run it myself with my environment to try the reproduce the issue.

[597-multisampler.tar.gz](https://github.com/choderalab/openmmtools/files/9056573/597-multisampler.tar.gz)

**Comment by zhang-ivy** [comment]
I just went back to find the code for you to reproduce the nc file and i realized i was not using the most recent openmmtools release (0.21.4). When I switch to a newer env that uses 0.21.4, I am not able to reproduce the problem. Closing this, as it must have been resolved at some point.
