### ISSUE TITLE
Adapt _get_equilibration_data_per_sample() to discard the first 1% of samples by default

### ISSUE THREAD

**Issue by zhang-ivy** [choderalab/openmmtools#609]
Change this line https://github.com/choderalab/openmmtools/blob/47f59f71aefe574b477a1a4949bd2ef653148c9e/openmmtools/multistate/utils.py#L180  to return `i_t[1:], g_i[1:], n_effective_i[1:]`

And make a note that the first 1% is being discarded due to equilibration because it throws off the t0 estimate otherwise
Note that the arrays returned will be of size `max_subset - 1`

**Comment by ijpulidos** [comment]
I wonder if we want to add a new optional parameter to the function to allow specifying the percentage of the samples we would like to discard. That is, if we want to be able to discard more or less in different scenarios, but keeping 1% as the default value.

**Comment by ijpulidos** [comment]
We want to make sure we use `ceiling` to round it up when we compute the number of samples.

**Comment by zhang-ivy** [comment]
@jchodera : I'm realizing that this fix isn't as simple as I thought it would be. In https://github.com/choderalab/openmmtools/pull/586, I introduced options for the user to specify the `statistical_inefficiency` and `n_equilibration_iterations`, but I think are problems with how I implemented it. 

The main function that is affected by the aforementioned PR is 
[`_get_equilibration_data()`](https://github.com/choderalab/openmmtools/blob/main/openmmtools/multistate/multistateanalyzer.py#L1998), which returns the following: 
```python
n_equilibration_iterations : int
    Number of equilibration iterations discarded
statistical_inefficiency : float
    Statistical inefficiency of production iterations
n_uncorrelated_iterations : float
    Effective number of uncorrelated iterations
``` 
Note that `n_uncorrelation_iterations` == `n_effective_max` below

There are multiple branches of logic in `_get_equilibration_data()` depending what the user has supplied to the `MultiStateSamplerAnalyzer`, let me walk through each of these branches: 

**Case 0:** Neither `n_equilibration_iterations` nor `statistical_inefficiency` are specified
- Compute the statistical inefficiency (using pymbar) for a bunch of t0s 
- `n_effective_max` -- `n_effective_samples` is computed from the pymbar-computed statistical inefficiencies and the maximum value is selected as `n_effective_max`
- `n_equilibration_iterations` is the t0 that maximizes `n_effective_samples` plus 1
-  `statistical_inefficiency` is the statistical inefficiency that corresponds to the selected `n_effective_max`

**Case 1:** User specifies both `statistical_inefficiency` and `n_equilibration_iterations`
- `statistical_inefficiency` -  return user specified one
- `n_equilibration_iterations` - return user specified one
- `n_effective_max` - is computed from `statistical_inefficiency`, `n_equilibration_iterations` , and `self.max_n_iterations` 

**Case 2:** User specifies `statistical_inefficiency` but not `n_equilibration_iterations`
- `statistical_inefficiency` - the statistical inefficiency is computed for a bunch of t0s using pymbar (like in case 0) but these are only used to compute the `n_effective_max` and `n_equlibration_iterations`, the user specified one is returned
- `n_effective_max` - `n_effective_samples` is computed from the (pymbar-computed and ignored) statistical inefficiencies and the maximum is selected as `n_effective_max`
- `n_equilibration_iterations` - is the t0 that maximizes `n_effective_samples` plus 1

Note: I don't think this is the behavior we want. I think `n_effective_max` should be computed from the user specified `statistical_inefficiency` using `(self.max_n_iterations - n_equilibration + 1) / statisitical_inefficiency`, but this expression requires knowledge of `n_equilibration_iterations`, which we normally compute based on the `n_effective_max`, leading to a circularity problem.

I'm not sure what the right way to fix this is. Should we require that `n_equilibration_iterations` must be specified if `statistical_inefficiency` is specified? 

**Case 3:** User specifies `n_equilibration_iterations` but not `statistical_inefficiency` 
- Discard `n_equilibration_iterations` from `u_n` and then compute the statistical inefficiencies for a bunch of t0s using pymbar (like in case 0) 
- `n_effective_max` -- `n_effective_samples` is computed from the pymbar-computed statistical inefficiencies and the maximum value is selected as `n_effective_max`
- `n_equilibration_iterations` - return user specified one, ignore the t0 that maximizes `n_effective_samples`
-  `statistical_inefficiency` is the statistical inefficiency that corresponds to the selected `n_effective_max`

Note the problem here is that `n_equilibration_iterations` does not include the t0 that maximizes `n_effective_samples`. I think `n_equilibration_iterations` should actually be the user specified value + the t0 that maximizes `n_effective_samples`

Now back to the actual point of this issue, which was to find a way to prevent `n_equilibration_iterations` from being 0 by discarding some samples from `u_n` before computing the statistical inefficiency for a bunch of t0s. There is a note here that the original fix for this `n_equilibration_iterations=0` issue was to always discard the first frame of `u_n`: https://github.com/choderalab/openmmtools/blob/main/openmmtools/multistate/multistateanalyzer.py#L2049-L2051

Therefore, since there was already an attempted fix for this problem, I think it would be simpler and more intuitive to modify `t0`  [here](https://github.com/choderalab/openmmtools/blob/main/openmmtools/multistate/multistateanalyzer.py#L2038) and hard code it to something like 10, but allow the user to override this by specifying `n_equilibration_iterations`. 

I don't think we should discard the first 1% of samples because if there are 10,000 or 100,000 samples, then we would be discarding 100 and 1,000 samples, respectively. That seems like a huge waste of data -- I think we just need to discard the first few frame, meaning 10 should be safe. What do you think?

**Comment by jchodera** [comment]
> I don't think we should discard the first 1% of samples because if there are 10,000 or 100,000 samples, then we would be discarding 100 and 1,000 samples, respectively. That seems like a huge waste of data -- I think we just need to discard the first few frames, meaning 10 should be safe. What do you think?

I didn't think it would be all that bad to discard just 1% of the data, but I think this is the point of allowing the user to specify the number of time origins to evaluate when identifying the optimal equilibration transition point: By default, 100 will discard no more than 1% of the data. If you're willing to wait longer, you can specify 1000. But we should probably always ignore the first time origin and consider the rest for potential equilibration starts.
