### ISSUE TITLE
Load serialized files generated with openmmtools<=0.21.2

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/openmmtools#612]
When trying to load simulation results from netcdf files generated with `openmmtools<=0.21.2` we encounter that the velocities are not present, since they were added in [0.21.3](https://github.com/choderalab/openmmtools/releases/tag/0.21.3). This results in an error when deserializing as follows
```
openmmtools.multistate.multistatesampler.MultiStateSampler._throw_restoration_error.<locals>.RestorationError: Attempting to restore from any checkpoint failed. Either your data is fully corrupted or something has gone very wrong to see this message. Please open an issue on the GitHub issue tracker if you see this!
```
We should be able to read older serialized `.nc` files with up to date versions of `openmmtools`. We could just try catching the `KeyError` exception when attempting to restore the velocities [here](https://github.com/choderalab/openmmtools/blob/cec8c3d6627d50e638daf79c759ec670a4fddff3/openmmtools/multistate/multistatereporter.py#L1727).

**Comment by jchodera** [comment]
Catching the KeyError to make this backward compatible sounds like a good
idea!
