### ISSUE TITLE
Documentation for Parallel Tempering is not properly generated

### ISSUE THREAD

**Issue by yihengwuKP** [choderalab/openmmtools#620]
I recently notice that the documentation for [parallel tempering](https://openmmtools.readthedocs.io/en/latest/multistate.html#parallel-tempering) is empty but the docstring is present in the [code](https://github.com/choderalab/openmmtools/blob/main/openmmtools/multistate/paralleltempering.py). Presumably the workflow of the generation of the documentation is broken somewhere?

**Comment by mikemhenry** [comment]
Thank you for pointing this out @yihengwuKP we are probably missing a call to autodoc somewhere. We will look into it!

**Comment by jchodera** [comment]
Thanks for catching this! None of the [multistate samplers](https://openmmtools.readthedocs.io/en/stable/multistate.html) have their API docs being rendered.

I believe this can happen when the module cannot be imported in the sphinx build environment. It's possible our required dependencies changed but the sphinx dependency list was not updated.

**Comment by mikemhenry** [comment]
Resolved with #622

**Comment by mikemhenry** [comment]
Note you will have to select "latest" for the docs to render, since the most recent stable version is broken, but will be fixed on next release.

**Comment by yihengwuKP** [comment]
cool, thanks!
