### ISSUE TITLE
About ReplicaExchangeSampler 

### ISSUE THREAD

**Issue by xiki-tempula** [choderalab/openmmtools#631]
In the https://openmmtools.readthedocs.io/en/stable/gettingstarted.html#example-a-minimal-implementation-of-a-general-replica-exchange-simulation-class, it is mentioned that 

> Our most recent enhanced-sampling facilities are currently hosted in [YANK](http://getyank.org/latest/api/multistate_api/index.html), and they are still waiting to be moved to OpenMMTools.

This kind of implies that the replica exchange is not implemented yet. I could see that there is a ReplicaExchangeSampler, I wonder if it is possible to update the `gettingstarted` page and show how this can be used? Thank you.

**Comment by Dan-Burns** [comment]
https://github.com/PotoyanGroup/MD-cookbook

There is an example in remd-sims.py in the above repository that will work for starting a simulation.

However with my system, I have not been able to produce anything other than an empty .nc file whose size doesn't change and is too small to contain a trajectory.  In one case, the simulation errored out after half a day, leaving logs that made it look like it had just reached the first exchange attempt.

If you are able to get it working, please let me know.

**Comment by xiki-tempula** [comment]
@Dan-Burns I got the issue of not being able to write the trajectory as well https://github.com/choderalab/openmmtools/issues/638.

**Comment by ijpulidos** [comment]
Thanks for the feedback! This is definitely something that should be improved with the documentation. Even the objects have [docstrings with examples](https://github.com/choderalab/openmmtools/blob/2e64980d86cf087f69e282927eebf2b41b73a3ea/openmmtools/multistate/replicaexchange.py#L113-L206) that may help users figure out how to use them.

Maybe just by having a _raw_ "API reference" in the documentation page will help with these cases.

**Comment by ijpulidos** [comment]
> https://github.com/PotoyanGroup/MD-cookbook
> 

The link is not working (throwing 404), maybe it is a private repo? 

> There is an example in remd-sims.py in the above repository that will work for starting a simulation.
> 
> However with my system, I have not been able to produce anything other than an empty .nc file whose size doesn't change and is too small to contain a trajectory. In one case, the simulation errored out after half a day, leaving logs that made it look like it had just reached the first exchange attempt.
> 
> If you are able to get it working, please let me know.

However, this seems like a different issue compared to the one being talked about in this ticket. I encourage you to report it in a separate issue with a minimal reproducible example. Thanks for the feedback!

**Comment by Dan-Burns** [comment]
@ljpulidos Sorry, I forgot that is a private repo.  I will follow up on my issue in a separate thread.

**Comment by ijpulidos** [comment]
Closing. Feel free to re-open if you think this is still an issue.
