### ISSUE TITLE
NetCDF files set the application to YANK - change to openmmtools?

### ISSUE THREAD

**Issue by IAlibay** [choderalab/openmmtools#694]
See: https://github.com/choderalab/openmmtools/blob/e4616ac44fe4bdf73aec5b8e129e90fe9c761a58/openmmtools/multistate/multistatereporter.py#L409

We've had confused users about this, can we change this to openmmtools?

**Comment by mikemhenry** [comment]
That is a ~5 year old part of the code base, @jchodera will have a better idea about the ramifications of that change. Is this pure metadata?
https://github.com/choderalab/openmmtools/blob/e4616ac44fe4bdf73aec5b8e129e90fe9c761a58/openmmtools/multistate/multistatereporter.py#L409-L410

**Comment by IAlibay** [comment]
_Should_ just be metadata (at least it is in the AMBER netcdf spec).

**Comment by mikemhenry** [comment]
@ijpulidos can you mention this to John at the next dev meeting?

**Comment by IAlibay** [comment]
> So we can remove `ncfile.program = 'yank.py'` and change `ncfile.application = 'YANK'` to `ncfile.application = 'openmmtools'` ?

@mikemhenry `program` is a required entry for the NetCDF convention, application is not 🙃 (so the other way around): https://ambermd.org/netcdf/nctraj.xhtml

**Comment by IAlibay** [comment]
I actually would advocate for `ncfile.program = f"openmmtools {openmmtools.__version__}"` that would significantly improve tracability.

**Comment by mikemhenry** [comment]
Solved with https://github.com/choderalab/openmmtools/pull/704
