### ISSUE TITLE
online_analysis_interval can no longer be None

### ISSUE THREAD

**Issue by xiki-tempula** [choderalab/openmmtools#708]
I want to disable the online_analysis_interval. In the doc (https://openmmtools.readthedocs.io/en/stable/api/generated/openmmtools.multistate.MultiStateSampler.html#openmmtools.multistate.MultiStateSampler), it is said that 

```
online_analysis_intervalNone or Int >= 1, optional, default: 200
Choose the interval at which to perform online analysis of the free energy.

After every interval, the simulation will be stopped and the free energy estimated.

If the error in the free energy estimate is at or below online_analysis_target_error, then the simulation will be considered completed.

If set to None, then no online analysis is performed
```

This used to work for the old versions, however in 0.23.0, I got the error of

```
  File "/tmp/pytest-of-zwu/pytest-6/test_difficult_molecule_C__C_H0/vac/prod/lambda_0/OpenMMTools_script.py", line 56, in <module>
    simulation.create(
  File "/exs/shared/collaboration/teams/mdteam/envs/asfe/lib/python3.10/site-packages/openmmtools/multistate/multistatesampler.py", line 595, in create
    if self.online_analysis_interval % self._reporter.checkpoint_interval != 0:
TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'
```

Please find the file to reproduce the bug.
[Archive.zip](https://github.com/choderalab/openmmtools/files/11917913/Archive.zip)

**Comment by mikemhenry** [comment]
Thank you for the bug report!

Sorry about that! I will add a check where we first check to see if it is `None` before we make sure that it is an interval.

**Comment by mikemhenry** [comment]
New `0.23.1` package is on conda-forge now which fixes this issue.
